//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=210.104.111.204;Initial Catalog=MAXUMS;Persist Security Info=True;Use" +
            "r ID=instsms;Password=instsms123")]
        public string RDBConnectionString {
            get {
                return ((string)(this["RDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.101")]
        public string snmpIP1 {
            get {
                return ((string)(this["snmpIP1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.17.111.127")]
        public string snmpIP2 {
            get {
                return ((string)(this["snmpIP2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.103")]
        public string snmpIP3 {
            get {
                return ((string)(this["snmpIP3"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com3")]
        public string TH1COM {
            get {
                return ((string)(this["TH1COM"]));
            }
            set {
                this["TH1COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com4")]
        public string TH2COM {
            get {
                return ((string)(this["TH2COM"]));
            }
            set {
                this["TH2COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com2")]
        public string HVIC1COM {
            get {
                return ((string)(this["HVIC1COM"]));
            }
            set {
                this["HVIC1COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com5")]
        public string HVIC2COM {
            get {
                return ((string)(this["HVIC2COM"]));
            }
            set {
                this["HVIC2COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com3")]
        public string LEAKCOM {
            get {
                return ((string)(this["LEAKCOM"]));
            }
            set {
                this["LEAKCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com8")]
        public string ELEC1COM {
            get {
                return ((string)(this["ELEC1COM"]));
            }
            set {
                this["ELEC1COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com9")]
        public string ELEC2COM {
            get {
                return ((string)(this["ELEC2COM"]));
            }
            set {
                this["ELEC2COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com10")]
        public string ELEC3COM {
            get {
                return ((string)(this["ELEC3COM"]));
            }
            set {
                this["ELEC3COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int ELEC3BITRATE {
            get {
                return ((int)(this["ELEC3BITRATE"]));
            }
            set {
                this["ELEC3BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int ELEC2BITRATE {
            get {
                return ((int)(this["ELEC2BITRATE"]));
            }
            set {
                this["ELEC2BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int ELEC1BITRATE {
            get {
                return ((int)(this["ELEC1BITRATE"]));
            }
            set {
                this["ELEC1BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int LEAKBITRATE {
            get {
                return ((int)(this["LEAKBITRATE"]));
            }
            set {
                this["LEAKBITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int HVIC2BITRATE {
            get {
                return ((int)(this["HVIC2BITRATE"]));
            }
            set {
                this["HVIC2BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int HVIC1BITRATE {
            get {
                return ((int)(this["HVIC1BITRATE"]));
            }
            set {
                this["HVIC1BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int TH2BITRATE {
            get {
                return ((int)(this["TH2BITRATE"]));
            }
            set {
                this["TH2BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int TH1BITRATE {
            get {
                return ((int)(this["TH1BITRATE"]));
            }
            set {
                this["TH1BITRATE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/WSDL/iLON100.WSDL")]
        public string FMS_Manager_WebReference_iLON100 {
            get {
                return ((string)(this["FMS_Manager_WebReference_iLON100"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;User Id=root;password=sem1234;Persist Security Info=True;databas" +
            "e=fmsdb")]
        public string fmsDBConnectionString {
            get {
                return ((string)(this["fmsDBConnectionString"]));
            }
        }
    }
}
